const products = [
    {
        title: "Crew neck T-shirt",
        image: "https://assets.ajio.com/medias/sys_master/root/20220217/zwxS/620d4e7caeb26921af9ba423/teamspirit_beige_structure_striped_crew-neck_t-shirt.jpg",
        price: 2064,
        productType: "t-shirt",
        size: "xl",
        category: "men",
        id: crypto.randomUUID(),
    },
    {
        title: "Typographic print T-shirt",
        image: "https://assets.ajio.com/medias/sys_master/root/20220505/Hm1K/6272c638f997dd03e2947272/dnmx_white_world_typographic_print_crew-neck_t-shirt.jpg",
        price: 2016,
        productType: "t-shirt",
        size: "sm",
        category: "men",
        id: crypto.randomUUID(),
    },
    {
        title: "Heathered track pant",
        image: "https://assets.ajio.com/medias/sys_master/root/20221216/qkVZ/639ca691aeb269659cf05052/teamspirit_charcoal_grey_heathered_track_pants_with_contrast_taping.jpg",
        price: 5000,
        productType: "pant",
        size: "32",
        category: "men",
        id: crypto.randomUUID(),
    },
    {
        title: "Slim fit joggers",
        image: "https://assets.ajio.com/medias/sys_master/root/20230301/xWKx/63ff8e1caeb26924e39cf1b3/mvmt_black_slim_fit_joggers_with_insert_pockets.jpg",
        price: 2000,
        productType: "pant",
        size: "28",
        category: "men",
        id: crypto.randomUUID(),
    },
    {
        title: "The bear house checks",
        image: "https://assets.ajio.com/medias/sys_master/root/20230602/m4NR/64793b5f42f9e729d70d68a6/the_bear_house_maroon_checked_slim_fit_shirt_with_patch_pocket.jpg",
        price: 1000,
        productType: "shirt",
        size: "l",
        category: "men",
        id: crypto.randomUUID(),
    },
    {
        title: "Printed straight kurta",
        image: "https://assets.ajio.com/medias/sys_master/root/20220830/5yAp/630dfb79f997dd1f8dc7bcf6/fashor_multicoloured_printed_straight_kurta.jpg",
        price: 4284,
        productType: "kurta",
        size: "xl",
        category: "women",
        id: crypto.randomUUID(),
    },
    {
        title: "Floral straight kurta",
        image: "https://assets.ajio.com/medias/sys_master/root/20230321/RqhE/6419b3a9aeb26924e3e68d34/fashor_off_white_floral_straight_kurta.jpg",
        price: 1029,
        productType: "kurta",
        size: "l",
        category: "women",
        id: crypto.randomUUID(),
    },
    {
        title: "Kanjeevaram saree",
        image: "https://assets.ajio.com/medias/sys_master/root/20230523/3GBn/646ca3d442f9e729d7a494b6/besucher_peach_woven_kanjeevaram_soft_silk_saree_with_zari_accent.jpg",
        price: 3297,
        productType: "saree",
        size: "xl",
        category: "women",
        id: crypto.randomUUID(),
    },
    {
        title: "Floral print saree",
        image: "https://assets.ajio.com/medias/sys_master/root/20230224/W8K3/63f926a0aeb26924e38e6eb6/gorgone_navy_blue_floral_print_saree.jpg",
        price: 3721,
        productType: "saree",
        size: "null",
        category: "women",
        id: crypto.randomUUID(),
    },
    {
        title: "Floral printed skirt",
        image: "https://assets.ajio.com/medias/sys_master/root/20220706/Eh6F/62c49711aeb26921af656fa7/fusion_maroon_floral_print_flared_skirt.jpg",
        price: 1023,
        productType: "skirt",
        size: "null",
        category: "women",
        id: crypto.randomUUID(),
    },
    {
        title: "Floral print palazoos",
        image: "https://assets.ajio.com/medias/sys_master/root/20220530/SLY1/6294deb5aeb26921aff4f178/tag_7_plus_navy_blue_floral_print_flared_palazzos.jpg",
        price: 2000,
        productType: "palazoos",
        size: "sm",
        category: "women",
        id: crypto.randomUUID(),
    },
    {
        title: "Polo T-shirt",
        image: "https://assets.ajio.com/medias/sys_master/root/20230302/Ky86/64004506f997dde6f4d794d7/tommy_hilfiger_multicoloured_striped_kb_ss_archive_polo_t-shirt.jpg",
        price: 2828,
        productType: "t-shirt",
        size: "sm",
        category: "kids",
        id: crypto.randomUUID(),
    },
    {
        title: "Flare dress",
        image: "https://assets.ajio.com/medias/sys_master/root/20230518/y72O/646582f2d55b7d0c63c1c9a2/tior_white_floral_print_fit_%26_flare_dress.jpg",
        price: 2585,
        productType: "dress",
        size: "",
        category: "kids",
        id: crypto.randomUUID(),
    },
    {
        title: "Cargo joggers",
        image: "https://assets.ajio.com/medias/sys_master/root/20230313/YDnE/640f52eaf997dde6f4f4e609/inf_frendz_olive_green_cargo_joggers_with_drawstring_waist.jpg",
        price: 3500,
        productType: "pant",
        size: "sm",
        category: "kids",
        id: crypto.randomUUID(),
    },
    {
        title: "Duck print rompers",
        image: "https://assets.ajio.com/medias/sys_master/root/20211231/5Fc1/61cf1d57f997dd66230c09c4/inf_frendz_multicoloured_pack_of_2_donald_duck_print_rompers.jpg",
        price: 3399,
        productType: "rompers",
        size: "xsm",
        category: "kids",
        id: crypto.randomUUID(),
    },
    {
        title: "Checked dress",
        image: "https://assets.ajio.com/medias/sys_master/root/20221221/m6Sd/63a324e4aeb269659cffbc21/inf_frendz_light_yellow_checked_fit_%26_flare_dress_with_bow_applique.jpg",
        price: 4789,
        productType: "dress",
        size: "xsm",
        category: "kids",
        id: crypto.randomUUID(),
    },
    {
        title: "Smart watch",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/files/Storm_Call.jpg?v=1682408982",
        price: 4000,
        category: "accessories",
        productType: "watch",
        id: crypto.randomUUID(),
    },
    {
        title: "Boat Airpods",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/files/131_new_8c8dd689-e23d-4448-9920-2ef3f5a5e43b.jpg?v=1685686859",
        price: 2999,
        category: "accessories",
        productType: "airpods",
        id: crypto.randomUUID(),
    },
    {
        title: "Party pal 53",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/products/main---1_14fdb862-156c-4161-a402-b4e56a464ec1_300x.png?v=1678952224",
        price: 1020,
        category: "accessories",
        productType: "speakers",
        id: crypto.randomUUID(),
    },
    {
        title: "Avant bar",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/products/1_9cff3830-58e0-4c29-89fc-1064ef7c632d_300x.png?v=1673376812",
        price: 4695,
        category: "accessories",
        productType: "speaker",
        id: crypto.randomUUID(),
    },
    {
        title: "Gaming headphones",
        image: "https://cdn.shopify.com/s/files/1/0057/8938/4802/products/2_f3aa2756-01f3-4e39-80bc-7b4f6551c7aa_300x.png?v=1625748159",
        price: 2000,
        category: "accessories",
        productType: "headphones",
        id: crypto.randomUUID(),
    },
];

export default products;
